server:
  port: 2224

cxf:
  path: /
  jaxrs:
    component-scan: true
    classes-scan-packages: org.codehaus.jackson.jaxrs

car-sharing-app:
  aws:
    s3:
      credentials:
        region: eu-north-1
        access-key: AKIAWJSX4WDT26A7DT2K
        secret-key: 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
      bucket-name: petproject-cars-s3-bucket-2021
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    topic-name: s3_car_topic